language: csharp
solution: OpenClassic.sln
mono: none
dotnet: 1.0.0-preview2-003131
dist: trusty

os:
  - linux

branches:
  only:
    - master

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CLI_VERSION=1.0.0-preview2-003131

# Make sure build dependencies are installed.
before_install:
  # - if test "$TRAVIS_OS_NAME" == "osx"; then ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
  
#install:
#  - travis_retry curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"

# Run the build script
script:
  - dotnet restore --disable-parallel
  - dotnet build ./src/OpenClassic.Server
  - dotnet build ./test/OpenClassic.Server.Tests
  #- dotnet test ./test/OpenClassic.Server.Tests # TODO: Get the unit tests running on CI build.
